version: "3.8"

services:
  php:
    image: dj:php-website
    container_name: "${DOMAIN_COM}"
    restart: unless-stopped
    user: 33:33
    volumes:
      - /opt/docker/${DOMAIN_COM}:/var/www
    networks:
      - web_network

networks:
  web_network:
    external: true
    name: ${NETWORK:-web_network}
