version: "3.8"

services:
  php:
    image: php-website:local
    container_name: { { domain_com } }
    restart: unless-stopped
    volumes:
      - /opt/docker/{{domain_com}}:/var/www/html
    networks:
      - web-network

networks:
  web-network:
    external: true
    name: web-network
